### ISSUE TITLE
cannot build after flutter update

### ISSUE THREAD

**Issue by letisoft** [umair13adil/flutter_logs#34]
Hello,

I am getting following error after flutter update:

pub.dartlang.org\flutter_logs-2.1.5\android\src\main\kotlin\com\flutter\logs\plogs\flutter_logs\FlutterLogsPlugin.kt: (43, 32): Type mismatch: inferred type is Activity? but Context was expected

Any idea?

**Comment by ASPIRINmoe** [comment]
i suggested a fix #33 ,but temporary you can build via git from [my fork](https://github.com/ASPIRINmoe/flutter_logs)

```yaml
  flutter_logs:
    git:
      url: https://github.com/ASPIRINmoe/flutter_logs.git
      ref: master
```
